version: "3.9"
services: 
    openjdk:
        container_name: kaizo_development
        stdin_open: true
        tty: true
        image: cmunroe/spigot:1.16.5
        volumes: 
            - ./testserver:/data
        ports: 
            - 25565:25565
        environment:
            - EULA=true
